export const ADD_FETCHED_DATA = 'ADD_FETCHED_DATA';
export const GET_DETAIL_POKEMON = 'GET_DETAIL_POKEMON'
export const ADD_FETCHED_DATA_POKEMON_TYPE = 'ADD_FETCHED_DATA_POKEMON_TYPE'
export const ADD_FETCHED_DATA_POKEMON_TYPE_DETAIL = 'ADD_FETCHED_DATA_POKEMON_TYPE_DETAIL'